services:
  postgres:
    image: postgres:15-alpine
    container_name: notify-postgres
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notify_user
      POSTGRES_PASSWORD: notify_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notify_user -d notifications"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
